version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=llm_gateway
      - REDIS_URL=redis://redis:6379
      - ADMIN_API_KEY=admin-secure-key-change-me
      - LOG_LEVEL=INFO
      # Provider API keys (uncomment and set your keys)
      # - OPENAI_API_KEY=sk-your-openai-key-here
      # - ANTHROPIC_API_KEY=sk-ant-your-anthropic-key-here
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=llm_gateway
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: